/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islandgame;

/**
 *
 * @author steph
 */
public class JobSelectScreen extends javax.swing.JFrame {
    TitleScreen firstWindow;
    public static int job;
    /**
     * Creates new form SecondScreen
     */
    public JobSelectScreen() {
        initComponents();
    }
    private Intro introScreen;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnHunter = new javax.swing.JButton();
        btnScout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 928, 793));
        setMinimumSize(new java.awt.Dimension(928, 637));
        setResizable(false);
        setSize(new java.awt.Dimension(928, 637));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        btnHunter.setText("Hunter!");
        btnHunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHunterActionPerformed(evt);
            }
        });
        getContentPane().add(btnHunter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        btnScout.setText("Boy Scout!");
        btnScout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnScout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/islandgame/Background layers/IslandGame_Hunter.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 210, 460, 340));

        lblTitle.setFont(new java.awt.Font("Stencil Std", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(210, 17, 0));
        lblTitle.setText("CHOOSE YOUR CLASS");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/islandgame/Background layers/IslandGame_Scout.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        firstWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHunterActionPerformed
        //Check if the Intro JFrame has been created
        if (introScreen == null){
            introScreen = new Intro(this);
        }
        //Make it visible
        introScreen.setVisible(true);
        //Hide this one
        this.setVisible(false);
        job = 0;
    }//GEN-LAST:event_btnHunterActionPerformed

    private void btnScoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoutActionPerformed
        //Check if the Intro JFrame has been created
        if (introScreen == null){
            introScreen = new Intro(this);
        }
        //Make it visible
        introScreen.setVisible(true);
        //Hide this one
        this.setVisible(false);
        job = 1;
    }//GEN-LAST:event_btnScoutActionPerformed

    /**
     * @param m
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHunter;
    private javax.swing.JButton btnScout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
    
    public JobSelectScreen(TitleScreen m){
        initComponents();
        firstWindow = m;
    }
}
