/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islandgame;

/**
 *
 * @author steph
 */
public class Intro extends javax.swing.JFrame {

    SecondScreen jobSelectWindow;//Previous window
    private Game gameWindow;//Next window
    int counter = 0;
    String firstMessage = "";
    String secondMessage = "";
    /**
     * Creates new form Intro
     */
    public Intro(SecondScreen j) {
        initComponents();
        jobSelectWindow = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(928, 637));
        setMinimumSize(new java.awt.Dimension(928, 637));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back to character select");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Papyrus", 0, 48)); // NOI18N
        jScrollPane1.setMaximumSize(new java.awt.Dimension(928, 637));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(928, 637));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(928, 637));
        jScrollPane1.setWheelScrollingEnabled(false);

        txtOut.setEditable(false);
        txtOut.setColumns(20);
        txtOut.setFont(new java.awt.Font("Papyrus", 0, 48)); // NOI18N
        txtOut.setRows(4);
        txtOut.setUI(null);
        txtOut.setAutoscrolls(false);
        txtOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtOut.setMaximumSize(new java.awt.Dimension(928, 637));
        txtOut.setMinimumSize(new java.awt.Dimension(928, 637));
        jScrollPane1.setViewportView(txtOut);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 928, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jobSelectWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        counter++;
        switch (counter) {
            case 1:
                txtOut.setText(firstMessage);
                break;
            case 2:
                txtOut.setText(secondMessage);
                break;
            case 3:
                if(gameWindow == null){
                    gameWindow = new Game(this);
                }   gameWindow.setVisible(true);
                this.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOut;
    // End of variables declaration//GEN-END:variables
}
